// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class Banner
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Titulo { get; set; }
        [Required]
        [StringLength(700)]
        public string Texto { get; set; }
        [StringLength(200)]
        public string TextoBoton { get; set; }
        [StringLength(700)]
        public string LinkBoton { get; set; }
        [Required]
        [StringLength(500)]
        public string RutaImagenDestok { get; set; }
        [Required]
        [StringLength(500)]
        public string RutaImagenMobile { get; set; }
        [Required]
        public bool? EsActivo { get; set; }
        public bool EsEliminado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaModif { get; set; }
        public int Orden { get; set; }
    }
}