// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class Categoria
    {
        public Categoria()
        {
            Servicio = new HashSet<Servicio>();
        }

        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(200)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        public string RutaImagen { get; set; }
        public bool? EsActivo { get; set; }

        [InverseProperty("IdCategoriaNavigation")]
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}