// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class ContactoLocal
    {
        public ContactoLocal()
        {
            HorarioAtencionLocal = new HashSet<HorarioAtencionLocal>();
            Profesional = new HashSet<Profesional>();
            ServicioContactoLocal = new HashSet<ServicioContactoLocal>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Nombre { get; set; }
        [Required]
        [StringLength(400)]
        public string Direccion { get; set; }
        [StringLength(80)]
        public string CoordenadaLatitud { get; set; }
        [StringLength(80)]
        public string CoordenadaLongitud { get; set; }
        [StringLength(30)]
        public string Telefono { get; set; }
        [StringLength(300)]
        public string Email { get; set; }
        public bool? EsActivo { get; set; }
        public bool EsEliminado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaModif { get; set; }
        public int Orden { get; set; }

        [InverseProperty("IdContactoLocalNavigation")]
        public virtual ICollection<HorarioAtencionLocal> HorarioAtencionLocal { get; set; }
        [InverseProperty("IdContactoLocalNavigation")]
        public virtual ICollection<Profesional> Profesional { get; set; }
        [InverseProperty("IdContactoLocalNavigation")]
        public virtual ICollection<ServicioContactoLocal> ServicioContactoLocal { get; set; }
    }
}