// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class CredencialMercadoPago
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(80)]
        public string Cuenta { get; set; }
        [Required]
        [Column("ClientID")]
        [StringLength(50)]
        public string ClientId { get; set; }
        [Required]
        [StringLength(50)]
        public string ClientSecret { get; set; }
        [Required]
        [StringLength(250)]
        public string AccessToken { get; set; }
        [Required]
        [StringLength(250)]
        public string PublicKey { get; set; }
        [Required]
        [StringLength(150)]
        public string RefreshToken { get; set; }
        public bool EsMarketPlace { get; set; }
        public bool EsSanbox { get; set; }
    }
}