// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class Dia
    {
        public Dia()
        {
            HorarioAtencionLocal = new HashSet<HorarioAtencionLocal>();
            HorarioAtencionProfesional = new HashSet<HorarioAtencionProfesional>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Nombre { get; set; }

        [InverseProperty("IdDiaNavigation")]
        public virtual ICollection<HorarioAtencionLocal> HorarioAtencionLocal { get; set; }
        [InverseProperty("IdDiaNavigation")]
        public virtual ICollection<HorarioAtencionProfesional> HorarioAtencionProfesional { get; set; }
    }
}