// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class HistoricoIngresos
    {
        [Key]
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaIngreso { get; set; }
        public bool? EsIngresoWeb { get; set; }
    }
}