// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace BarCejas.Entities
{
    public partial class HorarioBloqueado
    {
        [Key]
        public long Id { get; set; }
        public int IdProfesional { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaInicio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaFin { get; set; }
        public TimeSpan HoraInicio { get; set; }
        public TimeSpan HoraFin { get; set; }

        [ForeignKey(nameof(IdProfesional))]
        [InverseProperty(nameof(Profesional.HorarioBloqueado))]
        public virtual Profesional IdProfesionalNavigation { get; set; }
    }
}