// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class HorarioAtencionLocal
    {
        [Key]
        public int IdDia { get; set; }
        [Key]
        public int IdContactoLocal { get; set; }
        public TimeSpan HoraInicio { get; set; }
        public TimeSpan HoraFin { get; set; }

        [ForeignKey(nameof(IdContactoLocal))]
        [InverseProperty(nameof(ContactoLocal.HorarioAtencionLocal))]
        public virtual ContactoLocal IdContactoLocalNavigation { get; set; }
        [ForeignKey(nameof(IdDia))]
        [InverseProperty(nameof(Dia.HorarioAtencionLocal))]
        public virtual Dia IdDiaNavigation { get; set; }
    }
}