// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class MensajeMasivo
    {
        public MensajeMasivo()
        {
            RolTipoUsuarioMensajeMasivo = new HashSet<RolTipoUsuarioMensajeMasivo>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaModificacion { get; set; }
        public int IdUsuarioAlta { get; set; }
        public int IdUsuarioModificacion { get; set; }
        public bool EsEliminado { get; set; }

        [ForeignKey(nameof(IdUsuarioAlta))]
        [InverseProperty(nameof(Usuario.MensajeMasivoIdUsuarioAltaNavigation))]
        public virtual Usuario IdUsuarioAltaNavigation { get; set; }
        [ForeignKey(nameof(IdUsuarioModificacion))]
        [InverseProperty(nameof(Usuario.MensajeMasivoIdUsuarioModificacionNavigation))]
        public virtual Usuario IdUsuarioModificacionNavigation { get; set; }
        [InverseProperty("IdMensajeMasivoNavigation")]
        public virtual ICollection<RolTipoUsuarioMensajeMasivo> RolTipoUsuarioMensajeMasivo { get; set; }
    }
}