// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class ModalidadPagoServicio
    {
        [Key]
        public int Id { get; set; }
        public long IdServicio { get; set; }
        public int IdModalidadPago { get; set; }
        [Required]
        public bool? EsActivo { get; set; }

        [ForeignKey(nameof(IdModalidadPago))]
        [InverseProperty(nameof(ModalidadPago.ModalidadPagoServicio))]
        public virtual ModalidadPago IdModalidadPagoNavigation { get; set; }
        [ForeignKey(nameof(IdServicio))]
        [InverseProperty(nameof(Servicio.ModalidadPagoServicio))]
        public virtual Servicio IdServicioNavigation { get; set; }
    }
}