// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class ModalidadPago
    {
        public ModalidadPago()
        {
            ModalidadPagoServicio = new HashSet<ModalidadPagoServicio>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Nombre { get; set; }
        public bool? EsActivo { get; set; }

        [InverseProperty("IdModalidadPagoNavigation")]
        public virtual ICollection<ModalidadPagoServicio> ModalidadPagoServicio { get; set; }
    }
}