// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class Novedades
    {
        [Key]
        public long Id { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(200, ErrorMessage = "No puede contener más de 200 caracteres.")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(250, ErrorMessage = "No puede contener más de 250 caracteres.")]
        public string Copete { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        public string Contenido { get; set; }

        [StringLength(100, ErrorMessage = "No puede contener más de 100 caracteres.")]
        public string Medio { get; set; }

        [RegularExpression(@"(^https?:\/\/[\w\-]+(\.[\w\-]+)+[/#?]?.*)$", ErrorMessage = "Formato incorrecto.Debe ingresar un valor de la siguiente forma https://www.google.co.ve")]
        public string Link { get; set; }
        [Column(TypeName = "date")]
        [Required(ErrorMessage = "Campo requerido.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }
        public bool IndEstatus { get; set; }
        public bool IndHome { get; set; }
        public string RutaImagen { get; set; }
    }
}