// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class Orden
    {
        [Key]
        public int Id { get; set; }
        public int IdEstatus { get; set; }
        public int IdEstatusPago { get; set; }
        public int? IdModalidadPago { get; set; }
        public int IdFormaPago { get; set; }
        public int IdCliente { get; set; }
        public int IdPaquete { get; set; }
        public int IdContactoLocal { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? MontoPaquete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaDeCreacion { get; set; }
        [ForeignKey(nameof(IdModalidadPago))]
        public virtual ModalidadPago IdModalidadPagoNavigation { get; set; }
        [ForeignKey(nameof(IdCliente))]
        public virtual Usuario IdClienteNavigation { get; set; }
        [ForeignKey(nameof(IdContactoLocal))]
        public virtual ContactoLocal IdContactoLocalNavigation { get; set; }
        public string ComprobantePago { get; set; }
    }
}