// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class PreguntasFrecuentes
    {
        [Key]
        public long Id { get; set; }
        [Required(ErrorMessage = "Campo requerido.") ]
        [StringLength(250)]
        public string Pregunta { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(400)]
        public string Respuesta { get; set; }
        public int Orden { get; set; }
        public bool IndEstatus { get; set; }
        public bool EsEliminado { get; set; }
    }
}