// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    [Table("RolTipoUsuario_MensajeMasivo")]
    public partial class RolTipoUsuarioMensajeMasivo
    {
        [Key]
        public int IdMensajeMasivo { get; set; }
        [Key]
        public int IdTipoUsuario { get; set; }
        [Required]
        public bool? EsActivo { get; set; }

        [ForeignKey(nameof(IdMensajeMasivo))]
        [InverseProperty(nameof(MensajeMasivo.RolTipoUsuarioMensajeMasivo))]
        public virtual MensajeMasivo IdMensajeMasivoNavigation { get; set; }
    }
}