// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class ServicioProfesional
    {
        [Key]
        public int Id { get; set; }
        public long? IdServicio { get; set; }
        public int? IdProfesional { get; set; }
        [Required]
        public bool? EsActivo { get; set; }

        [ForeignKey(nameof(IdProfesional))]
        [InverseProperty(nameof(Profesional.ServicioProfesional))]
        public virtual Profesional IdProfesionalNavigation { get; set; }
        [ForeignKey(nameof(IdServicio))]
        [InverseProperty(nameof(Servicio.ServicioProfesional))]
        public virtual Servicio IdServicioNavigation { get; set; }
    }
}