// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class ServicioPaquete
    {
        [Key]
        public int Id { get; set; }
        public long? IdPaquete { get; set; }
        public long? IdServicio { get; set; }
        public int Cantidad { get; set; }
        [Required]
        public bool? EsActivo { get; set; }

        [ForeignKey(nameof(IdPaquete))]
        [InverseProperty(nameof(Paquete.ServicioPaquete))]
        public virtual Paquete IdPaqueteNavigation { get; set; }
        [ForeignKey(nameof(IdServicio))]
        [InverseProperty(nameof(Servicio.ServicioPaquete))]
        public virtual Servicio IdServicioNavigation { get; set; }
    }
}