// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class Testimonios
    {
        [Key]
        public long Id { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(300, ErrorMessage = "No puede contener más de 300 caracteres.")]
        public string Testimonio { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Formato incorrecto.Debe ingresar solo letras")]
        [StringLength(100, ErrorMessage = "No puede contener más de 100 caracteres.")]
        public string Autor { get; set; }

        public string RutaImagen { get; set; }
        public int Orden { get; set; }
        public bool IndActivo { get; set; }
        public bool EsEliminado { get; set; }
    }
}