// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarCejas.Entities
{
    public partial class Usuario
    {
        public Usuario()
        {
            MensajeMasivoIdUsuarioAltaNavigation = new HashSet<MensajeMasivo>();
            MensajeMasivoIdUsuarioModificacionNavigation = new HashSet<MensajeMasivo>();
            Profesional = new HashSet<Profesional>();
            Servicio = new HashSet<Servicio>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(250, ErrorMessage = "No puede contener más de 250 caracteres.")]
        public string Nombre { get; set; }
        [StringLength(250, ErrorMessage = "No puede contener más de 250 caracteres.")]
        public string Apellido { get; set; }
        [StringLength(25, ErrorMessage = "No puede contener más de 250 caracteres.")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(25, ErrorMessage = "No puede contener más de 25 caracteres.")]
        public string Genero { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(200, ErrorMessage = "No puede contener más de 200 caracteres.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(25)]
        public string Registro { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        public string Password { get; set; }
        [Column(TypeName = "date")]

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FechaNacimiento { get; set; }
        public int IdTipoUsuario { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        public int IdTipoGenero { get; set; }
        [Column("DNI")]
        [StringLength(100, ErrorMessage = "No puede contener más de 100 caracteres.")]
        public string Dni { get; set; }
        public bool? EsActivo { get; set; }

        [InverseProperty(nameof(MensajeMasivo.IdUsuarioAltaNavigation))]
        public virtual ICollection<MensajeMasivo> MensajeMasivoIdUsuarioAltaNavigation { get; set; }
        [InverseProperty(nameof(MensajeMasivo.IdUsuarioModificacionNavigation))]
        public virtual ICollection<MensajeMasivo> MensajeMasivoIdUsuarioModificacionNavigation { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<Profesional> Profesional { get; set; }
        [InverseProperty("IdUsuarioAltaNavigation")]
        public virtual ICollection<Servicio> Servicio { get; set; }
        public string Avatar { get; set; }
    }
}